#include "config.h"

// BASIC

float RATIO = 0.1f;
int WINDOW_WIDTH = 1080;
int WINDOW_HEIGHT = 760;
int DISPLAY_WIDTH = WINDOW_WIDTH * RATIO;
int DISPLAY_HEIGHT = WINDOW_HEIGHT * RATIO;

//ADVANCED
float UPDATE_INTERVAL = 0.025;
